package com.amecfw.sage.persistence;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.amecfw.sage.model.Owner;
import com.amecfw.sage.model.Project;
import com.amecfw.sage.model.Site;
import com.amecfw.sage.model.Location;
import com.amecfw.sage.model.LocationMeta;
import com.amecfw.sage.model.ProjectSite;
import com.amecfw.sage.model.ProjectSiteMeta;
import com.amecfw.sage.model.Coordinate;
import com.amecfw.sage.model.Element;
import com.amecfw.sage.model.ElementMeta;
import com.amecfw.sage.model.ElementGroup;
import com.amecfw.sage.model.ElementGroupMeta;
import com.amecfw.sage.model.GroupElement;
import com.amecfw.sage.model.Station;
import com.amecfw.sage.model.StationMeta;
import com.amecfw.sage.model.StationElement;
import com.amecfw.sage.model.StationElementMeta;
import com.amecfw.sage.model.ObservationType;
import com.amecfw.sage.model.ObservationGroup;
import com.amecfw.sage.model.ObservationGroupMeta;
import com.amecfw.sage.model.GroupObservation;
import com.amecfw.sage.model.GroupObservationMeta;
import com.amecfw.sage.model.Observation;
import com.amecfw.sage.model.ObservationMeta;
import com.amecfw.sage.model.Parameter;
import com.amecfw.sage.model.Measurement;
import com.amecfw.sage.model.MeasurementMeta;
import com.amecfw.sage.model.Photo;
import com.amecfw.sage.model.PhotoMeta;

import com.amecfw.sage.persistence.OwnerDao;
import com.amecfw.sage.persistence.ProjectDao;
import com.amecfw.sage.persistence.SiteDao;
import com.amecfw.sage.persistence.LocationDao;
import com.amecfw.sage.persistence.LocationMetaDao;
import com.amecfw.sage.persistence.ProjectSiteDao;
import com.amecfw.sage.persistence.ProjectSiteMetaDao;
import com.amecfw.sage.persistence.CoordinateDao;
import com.amecfw.sage.persistence.ElementDao;
import com.amecfw.sage.persistence.ElementMetaDao;
import com.amecfw.sage.persistence.ElementGroupDao;
import com.amecfw.sage.persistence.ElementGroupMetaDao;
import com.amecfw.sage.persistence.GroupElementDao;
import com.amecfw.sage.persistence.StationDao;
import com.amecfw.sage.persistence.StationMetaDao;
import com.amecfw.sage.persistence.StationElementDao;
import com.amecfw.sage.persistence.StationElementMetaDao;
import com.amecfw.sage.persistence.ObservationTypeDao;
import com.amecfw.sage.persistence.ObservationGroupDao;
import com.amecfw.sage.persistence.ObservationGroupMetaDao;
import com.amecfw.sage.persistence.GroupObservationDao;
import com.amecfw.sage.persistence.GroupObservationMetaDao;
import com.amecfw.sage.persistence.ObservationDao;
import com.amecfw.sage.persistence.ObservationMetaDao;
import com.amecfw.sage.persistence.ParameterDao;
import com.amecfw.sage.persistence.MeasurementDao;
import com.amecfw.sage.persistence.MeasurementMetaDao;
import com.amecfw.sage.persistence.PhotoDao;
import com.amecfw.sage.persistence.PhotoMetaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ownerDaoConfig;
    private final DaoConfig projectDaoConfig;
    private final DaoConfig siteDaoConfig;
    private final DaoConfig locationDaoConfig;
    private final DaoConfig locationMetaDaoConfig;
    private final DaoConfig projectSiteDaoConfig;
    private final DaoConfig projectSiteMetaDaoConfig;
    private final DaoConfig coordinateDaoConfig;
    private final DaoConfig elementDaoConfig;
    private final DaoConfig elementMetaDaoConfig;
    private final DaoConfig elementGroupDaoConfig;
    private final DaoConfig elementGroupMetaDaoConfig;
    private final DaoConfig groupElementDaoConfig;
    private final DaoConfig stationDaoConfig;
    private final DaoConfig stationMetaDaoConfig;
    private final DaoConfig stationElementDaoConfig;
    private final DaoConfig stationElementMetaDaoConfig;
    private final DaoConfig observationTypeDaoConfig;
    private final DaoConfig observationGroupDaoConfig;
    private final DaoConfig observationGroupMetaDaoConfig;
    private final DaoConfig groupObservationDaoConfig;
    private final DaoConfig groupObservationMetaDaoConfig;
    private final DaoConfig observationDaoConfig;
    private final DaoConfig observationMetaDaoConfig;
    private final DaoConfig parameterDaoConfig;
    private final DaoConfig measurementDaoConfig;
    private final DaoConfig measurementMetaDaoConfig;
    private final DaoConfig photoDaoConfig;
    private final DaoConfig photoMetaDaoConfig;

    private final OwnerDao ownerDao;
    private final ProjectDao projectDao;
    private final SiteDao siteDao;
    private final LocationDao locationDao;
    private final LocationMetaDao locationMetaDao;
    private final ProjectSiteDao projectSiteDao;
    private final ProjectSiteMetaDao projectSiteMetaDao;
    private final CoordinateDao coordinateDao;
    private final ElementDao elementDao;
    private final ElementMetaDao elementMetaDao;
    private final ElementGroupDao elementGroupDao;
    private final ElementGroupMetaDao elementGroupMetaDao;
    private final GroupElementDao groupElementDao;
    private final StationDao stationDao;
    private final StationMetaDao stationMetaDao;
    private final StationElementDao stationElementDao;
    private final StationElementMetaDao stationElementMetaDao;
    private final ObservationTypeDao observationTypeDao;
    private final ObservationGroupDao observationGroupDao;
    private final ObservationGroupMetaDao observationGroupMetaDao;
    private final GroupObservationDao groupObservationDao;
    private final GroupObservationMetaDao groupObservationMetaDao;
    private final ObservationDao observationDao;
    private final ObservationMetaDao observationMetaDao;
    private final ParameterDao parameterDao;
    private final MeasurementDao measurementDao;
    private final MeasurementMetaDao measurementMetaDao;
    private final PhotoDao photoDao;
    private final PhotoMetaDao photoMetaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ownerDaoConfig = daoConfigMap.get(OwnerDao.class).clone();
        ownerDaoConfig.initIdentityScope(type);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        siteDaoConfig = daoConfigMap.get(SiteDao.class).clone();
        siteDaoConfig.initIdentityScope(type);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        locationMetaDaoConfig = daoConfigMap.get(LocationMetaDao.class).clone();
        locationMetaDaoConfig.initIdentityScope(type);

        projectSiteDaoConfig = daoConfigMap.get(ProjectSiteDao.class).clone();
        projectSiteDaoConfig.initIdentityScope(type);

        projectSiteMetaDaoConfig = daoConfigMap.get(ProjectSiteMetaDao.class).clone();
        projectSiteMetaDaoConfig.initIdentityScope(type);

        coordinateDaoConfig = daoConfigMap.get(CoordinateDao.class).clone();
        coordinateDaoConfig.initIdentityScope(type);

        elementDaoConfig = daoConfigMap.get(ElementDao.class).clone();
        elementDaoConfig.initIdentityScope(type);

        elementMetaDaoConfig = daoConfigMap.get(ElementMetaDao.class).clone();
        elementMetaDaoConfig.initIdentityScope(type);

        elementGroupDaoConfig = daoConfigMap.get(ElementGroupDao.class).clone();
        elementGroupDaoConfig.initIdentityScope(type);

        elementGroupMetaDaoConfig = daoConfigMap.get(ElementGroupMetaDao.class).clone();
        elementGroupMetaDaoConfig.initIdentityScope(type);

        groupElementDaoConfig = daoConfigMap.get(GroupElementDao.class).clone();
        groupElementDaoConfig.initIdentityScope(type);

        stationDaoConfig = daoConfigMap.get(StationDao.class).clone();
        stationDaoConfig.initIdentityScope(type);

        stationMetaDaoConfig = daoConfigMap.get(StationMetaDao.class).clone();
        stationMetaDaoConfig.initIdentityScope(type);

        stationElementDaoConfig = daoConfigMap.get(StationElementDao.class).clone();
        stationElementDaoConfig.initIdentityScope(type);

        stationElementMetaDaoConfig = daoConfigMap.get(StationElementMetaDao.class).clone();
        stationElementMetaDaoConfig.initIdentityScope(type);

        observationTypeDaoConfig = daoConfigMap.get(ObservationTypeDao.class).clone();
        observationTypeDaoConfig.initIdentityScope(type);

        observationGroupDaoConfig = daoConfigMap.get(ObservationGroupDao.class).clone();
        observationGroupDaoConfig.initIdentityScope(type);

        observationGroupMetaDaoConfig = daoConfigMap.get(ObservationGroupMetaDao.class).clone();
        observationGroupMetaDaoConfig.initIdentityScope(type);

        groupObservationDaoConfig = daoConfigMap.get(GroupObservationDao.class).clone();
        groupObservationDaoConfig.initIdentityScope(type);

        groupObservationMetaDaoConfig = daoConfigMap.get(GroupObservationMetaDao.class).clone();
        groupObservationMetaDaoConfig.initIdentityScope(type);

        observationDaoConfig = daoConfigMap.get(ObservationDao.class).clone();
        observationDaoConfig.initIdentityScope(type);

        observationMetaDaoConfig = daoConfigMap.get(ObservationMetaDao.class).clone();
        observationMetaDaoConfig.initIdentityScope(type);

        parameterDaoConfig = daoConfigMap.get(ParameterDao.class).clone();
        parameterDaoConfig.initIdentityScope(type);

        measurementDaoConfig = daoConfigMap.get(MeasurementDao.class).clone();
        measurementDaoConfig.initIdentityScope(type);

        measurementMetaDaoConfig = daoConfigMap.get(MeasurementMetaDao.class).clone();
        measurementMetaDaoConfig.initIdentityScope(type);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        photoMetaDaoConfig = daoConfigMap.get(PhotoMetaDao.class).clone();
        photoMetaDaoConfig.initIdentityScope(type);

        ownerDao = new OwnerDao(ownerDaoConfig, this);
        projectDao = new ProjectDao(projectDaoConfig, this);
        siteDao = new SiteDao(siteDaoConfig, this);
        locationDao = new LocationDao(locationDaoConfig, this);
        locationMetaDao = new LocationMetaDao(locationMetaDaoConfig, this);
        projectSiteDao = new ProjectSiteDao(projectSiteDaoConfig, this);
        projectSiteMetaDao = new ProjectSiteMetaDao(projectSiteMetaDaoConfig, this);
        coordinateDao = new CoordinateDao(coordinateDaoConfig, this);
        elementDao = new ElementDao(elementDaoConfig, this);
        elementMetaDao = new ElementMetaDao(elementMetaDaoConfig, this);
        elementGroupDao = new ElementGroupDao(elementGroupDaoConfig, this);
        elementGroupMetaDao = new ElementGroupMetaDao(elementGroupMetaDaoConfig, this);
        groupElementDao = new GroupElementDao(groupElementDaoConfig, this);
        stationDao = new StationDao(stationDaoConfig, this);
        stationMetaDao = new StationMetaDao(stationMetaDaoConfig, this);
        stationElementDao = new StationElementDao(stationElementDaoConfig, this);
        stationElementMetaDao = new StationElementMetaDao(stationElementMetaDaoConfig, this);
        observationTypeDao = new ObservationTypeDao(observationTypeDaoConfig, this);
        observationGroupDao = new ObservationGroupDao(observationGroupDaoConfig, this);
        observationGroupMetaDao = new ObservationGroupMetaDao(observationGroupMetaDaoConfig, this);
        groupObservationDao = new GroupObservationDao(groupObservationDaoConfig, this);
        groupObservationMetaDao = new GroupObservationMetaDao(groupObservationMetaDaoConfig, this);
        observationDao = new ObservationDao(observationDaoConfig, this);
        observationMetaDao = new ObservationMetaDao(observationMetaDaoConfig, this);
        parameterDao = new ParameterDao(parameterDaoConfig, this);
        measurementDao = new MeasurementDao(measurementDaoConfig, this);
        measurementMetaDao = new MeasurementMetaDao(measurementMetaDaoConfig, this);
        photoDao = new PhotoDao(photoDaoConfig, this);
        photoMetaDao = new PhotoMetaDao(photoMetaDaoConfig, this);

        registerDao(Owner.class, ownerDao);
        registerDao(Project.class, projectDao);
        registerDao(Site.class, siteDao);
        registerDao(Location.class, locationDao);
        registerDao(LocationMeta.class, locationMetaDao);
        registerDao(ProjectSite.class, projectSiteDao);
        registerDao(ProjectSiteMeta.class, projectSiteMetaDao);
        registerDao(Coordinate.class, coordinateDao);
        registerDao(Element.class, elementDao);
        registerDao(ElementMeta.class, elementMetaDao);
        registerDao(ElementGroup.class, elementGroupDao);
        registerDao(ElementGroupMeta.class, elementGroupMetaDao);
        registerDao(GroupElement.class, groupElementDao);
        registerDao(Station.class, stationDao);
        registerDao(StationMeta.class, stationMetaDao);
        registerDao(StationElement.class, stationElementDao);
        registerDao(StationElementMeta.class, stationElementMetaDao);
        registerDao(ObservationType.class, observationTypeDao);
        registerDao(ObservationGroup.class, observationGroupDao);
        registerDao(ObservationGroupMeta.class, observationGroupMetaDao);
        registerDao(GroupObservation.class, groupObservationDao);
        registerDao(GroupObservationMeta.class, groupObservationMetaDao);
        registerDao(Observation.class, observationDao);
        registerDao(ObservationMeta.class, observationMetaDao);
        registerDao(Parameter.class, parameterDao);
        registerDao(Measurement.class, measurementDao);
        registerDao(MeasurementMeta.class, measurementMetaDao);
        registerDao(Photo.class, photoDao);
        registerDao(PhotoMeta.class, photoMetaDao);
    }
    
    public void clear() {
        ownerDaoConfig.getIdentityScope().clear();
        projectDaoConfig.getIdentityScope().clear();
        siteDaoConfig.getIdentityScope().clear();
        locationDaoConfig.getIdentityScope().clear();
        locationMetaDaoConfig.getIdentityScope().clear();
        projectSiteDaoConfig.getIdentityScope().clear();
        projectSiteMetaDaoConfig.getIdentityScope().clear();
        coordinateDaoConfig.getIdentityScope().clear();
        elementDaoConfig.getIdentityScope().clear();
        elementMetaDaoConfig.getIdentityScope().clear();
        elementGroupDaoConfig.getIdentityScope().clear();
        elementGroupMetaDaoConfig.getIdentityScope().clear();
        groupElementDaoConfig.getIdentityScope().clear();
        stationDaoConfig.getIdentityScope().clear();
        stationMetaDaoConfig.getIdentityScope().clear();
        stationElementDaoConfig.getIdentityScope().clear();
        stationElementMetaDaoConfig.getIdentityScope().clear();
        observationTypeDaoConfig.getIdentityScope().clear();
        observationGroupDaoConfig.getIdentityScope().clear();
        observationGroupMetaDaoConfig.getIdentityScope().clear();
        groupObservationDaoConfig.getIdentityScope().clear();
        groupObservationMetaDaoConfig.getIdentityScope().clear();
        observationDaoConfig.getIdentityScope().clear();
        observationMetaDaoConfig.getIdentityScope().clear();
        parameterDaoConfig.getIdentityScope().clear();
        measurementDaoConfig.getIdentityScope().clear();
        measurementMetaDaoConfig.getIdentityScope().clear();
        photoDaoConfig.getIdentityScope().clear();
        photoMetaDaoConfig.getIdentityScope().clear();
    }

    public OwnerDao getOwnerDao() {
        return ownerDao;
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

    public SiteDao getSiteDao() {
        return siteDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public LocationMetaDao getLocationMetaDao() {
        return locationMetaDao;
    }

    public ProjectSiteDao getProjectSiteDao() {
        return projectSiteDao;
    }

    public ProjectSiteMetaDao getProjectSiteMetaDao() {
        return projectSiteMetaDao;
    }

    public CoordinateDao getCoordinateDao() {
        return coordinateDao;
    }

    public ElementDao getElementDao() {
        return elementDao;
    }

    public ElementMetaDao getElementMetaDao() {
        return elementMetaDao;
    }

    public ElementGroupDao getElementGroupDao() {
        return elementGroupDao;
    }

    public ElementGroupMetaDao getElementGroupMetaDao() {
        return elementGroupMetaDao;
    }

    public GroupElementDao getGroupElementDao() {
        return groupElementDao;
    }

    public StationDao getStationDao() {
        return stationDao;
    }

    public StationMetaDao getStationMetaDao() {
        return stationMetaDao;
    }

    public StationElementDao getStationElementDao() {
        return stationElementDao;
    }

    public StationElementMetaDao getStationElementMetaDao() {
        return stationElementMetaDao;
    }

    public ObservationTypeDao getObservationTypeDao() {
        return observationTypeDao;
    }

    public ObservationGroupDao getObservationGroupDao() {
        return observationGroupDao;
    }

    public ObservationGroupMetaDao getObservationGroupMetaDao() {
        return observationGroupMetaDao;
    }

    public GroupObservationDao getGroupObservationDao() {
        return groupObservationDao;
    }

    public GroupObservationMetaDao getGroupObservationMetaDao() {
        return groupObservationMetaDao;
    }

    public ObservationDao getObservationDao() {
        return observationDao;
    }

    public ObservationMetaDao getObservationMetaDao() {
        return observationMetaDao;
    }

    public ParameterDao getParameterDao() {
        return parameterDao;
    }

    public MeasurementDao getMeasurementDao() {
        return measurementDao;
    }

    public MeasurementMetaDao getMeasurementMetaDao() {
        return measurementMetaDao;
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

    public PhotoMetaDao getPhotoMetaDao() {
        return photoMetaDao;
    }

}
