package com.amecfw.sage.persistence;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.amecfw.sage.model.Element;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ELEMENT.
*/
public class ElementDao extends AbstractDao<Element, Long> {

    public static final String TABLENAME = "ELEMENT";

    /**
     * Properties of entity Element.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RowGuid = new Property(1, String.class, "rowGuid", false, "ROW_GUID");
        public final static Property Scode = new Property(2, String.class, "scode", false, "SCODE");
        public final static Property ScientificName = new Property(3, String.class, "scientificName", false, "SCIENTIFIC_NAME");
        public final static Property CommonName = new Property(4, String.class, "commonName", false, "COMMON_NAME");
    };

    private DaoSession daoSession;


    public ElementDao(DaoConfig config) {
        super(config);
    }
    
    public ElementDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ELEMENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROW_GUID' TEXT NOT NULL UNIQUE ," + // 1: rowGuid
                "'SCODE' TEXT," + // 2: scode
                "'SCIENTIFIC_NAME' TEXT," + // 3: scientificName
                "'COMMON_NAME' TEXT);"); // 4: commonName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ELEMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Element entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRowGuid());
 
        String scode = entity.getScode();
        if (scode != null) {
            stmt.bindString(3, scode);
        }
 
        String scientificName = entity.getScientificName();
        if (scientificName != null) {
            stmt.bindString(4, scientificName);
        }
 
        String commonName = entity.getCommonName();
        if (commonName != null) {
            stmt.bindString(5, commonName);
        }
    }

    @Override
    protected void attachEntity(Element entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Element readEntity(Cursor cursor, int offset) {
        Element entity = new Element( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // rowGuid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // scode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // scientificName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // commonName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Element entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRowGuid(cursor.getString(offset + 1));
        entity.setScode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setScientificName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCommonName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Element entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Element entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
