package com.amecfw.sage.persistence;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.amecfw.sage.model.Element;
import com.amecfw.sage.model.ElementGroup;

import com.amecfw.sage.model.GroupElement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GROUP_ELEMENT.
*/
public class GroupElementDao extends AbstractDao<GroupElement, Long> {

    public static final String TABLENAME = "GROUP_ELEMENT";

    /**
     * Properties of entity GroupElement.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RowGuid = new Property(1, String.class, "rowGuid", false, "ROW_GUID");
        public final static Property Flags = new Property(2, String.class, "flags", false, "FLAGS");
        public final static Property ElementGroupID = new Property(3, Long.class, "elementGroupID", false, "ELEMENT_GROUP_ID");
        public final static Property ElementID = new Property(4, Long.class, "elementID", false, "ELEMENT_ID");
    };

    private DaoSession daoSession;

    private Query<GroupElement> elementGroup_GroupElementsQuery;

    public GroupElementDao(DaoConfig config) {
        super(config);
    }
    
    public GroupElementDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GROUP_ELEMENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROW_GUID' TEXT NOT NULL UNIQUE ," + // 1: rowGuid
                "'FLAGS' TEXT," + // 2: flags
                "'ELEMENT_GROUP_ID' INTEGER," + // 3: elementGroupID
                "'ELEMENT_ID' INTEGER);"); // 4: elementID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GROUP_ELEMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GroupElement entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRowGuid());
 
        String flags = entity.getFlags();
        if (flags != null) {
            stmt.bindString(3, flags);
        }
 
        Long elementGroupID = entity.getElementGroupID();
        if (elementGroupID != null) {
            stmt.bindLong(4, elementGroupID);
        }
 
        Long elementID = entity.getElementID();
        if (elementID != null) {
            stmt.bindLong(5, elementID);
        }
    }

    @Override
    protected void attachEntity(GroupElement entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GroupElement readEntity(Cursor cursor, int offset) {
        GroupElement entity = new GroupElement( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // rowGuid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // flags
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // elementGroupID
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // elementID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GroupElement entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRowGuid(cursor.getString(offset + 1));
        entity.setFlags(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setElementGroupID(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setElementID(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GroupElement entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GroupElement entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "groupElements" to-many relationship of ElementGroup. */
    public List<GroupElement> _queryElementGroup_GroupElements(Long elementGroupID) {
        synchronized (this) {
            if (elementGroup_GroupElementsQuery == null) {
                QueryBuilder<GroupElement> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ElementGroupID.eq(null));
                elementGroup_GroupElementsQuery = queryBuilder.build();
            }
        }
        Query<GroupElement> query = elementGroup_GroupElementsQuery.forCurrentThread();
        query.setParameter(0, elementGroupID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getElementGroupDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getElementDao().getAllColumns());
            builder.append(" FROM GROUP_ELEMENT T");
            builder.append(" LEFT JOIN ELEMENT_GROUP T0 ON T.'ELEMENT_GROUP_ID'=T0.'_id'");
            builder.append(" LEFT JOIN ELEMENT T1 ON T.'ELEMENT_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GroupElement loadCurrentDeep(Cursor cursor, boolean lock) {
        GroupElement entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ElementGroup elementGroup = loadCurrentOther(daoSession.getElementGroupDao(), cursor, offset);
        entity.setElementGroup(elementGroup);
        offset += daoSession.getElementGroupDao().getAllColumns().length;

        Element element = loadCurrentOther(daoSession.getElementDao(), cursor, offset);
        entity.setElement(element);

        return entity;    
    }

    public GroupElement loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GroupElement> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GroupElement> list = new ArrayList<GroupElement>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GroupElement> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GroupElement> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
