package com.amecfw.sage.persistence;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.amecfw.sage.model.Parameter;
import com.amecfw.sage.model.Station;

import com.amecfw.sage.model.Measurement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MEASUREMENT.
*/
public class MeasurementDao extends AbstractDao<Measurement, Long> {

    public static final String TABLENAME = "MEASUREMENT";

    /**
     * Properties of entity Measurement.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RowGuid = new Property(1, String.class, "rowGuid", false, "ROW_GUID");
        public final static Property DateMeasured = new Property(2, java.util.Date.class, "dateMeasured", false, "DATE_MEASURED");
        public final static Property TimeMeasured = new Property(3, java.util.Date.class, "timeMeasured", false, "TIME_MEASURED");
        public final static Property Matrix = new Property(4, String.class, "matrix", false, "MATRIX");
        public final static Property Unit = new Property(5, String.class, "unit", false, "UNIT");
        public final static Property Qualifier = new Property(6, String.class, "qualifier", false, "QUALIFIER");
        public final static Property MeasurementText = new Property(7, String.class, "measurementText", false, "MEASUREMENT_TEXT");
        public final static Property StationID = new Property(8, long.class, "stationID", false, "STATION_ID");
        public final static Property ParameterID = new Property(9, long.class, "parameterID", false, "PARAMETER_ID");
    };

    private DaoSession daoSession;


    public MeasurementDao(DaoConfig config) {
        super(config);
    }
    
    public MeasurementDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MEASUREMENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROW_GUID' TEXT NOT NULL UNIQUE ," + // 1: rowGuid
                "'DATE_MEASURED' INTEGER," + // 2: dateMeasured
                "'TIME_MEASURED' INTEGER," + // 3: timeMeasured
                "'MATRIX' TEXT," + // 4: matrix
                "'UNIT' TEXT," + // 5: unit
                "'QUALIFIER' TEXT," + // 6: qualifier
                "'MEASUREMENT_TEXT' TEXT," + // 7: measurementText
                "'STATION_ID' INTEGER NOT NULL ," + // 8: stationID
                "'PARAMETER_ID' INTEGER NOT NULL );"); // 9: parameterID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MEASUREMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Measurement entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRowGuid());
 
        java.util.Date dateMeasured = entity.getDateMeasured();
        if (dateMeasured != null) {
            stmt.bindLong(3, dateMeasured.getTime());
        }
 
        java.util.Date timeMeasured = entity.getTimeMeasured();
        if (timeMeasured != null) {
            stmt.bindLong(4, timeMeasured.getTime());
        }
 
        String matrix = entity.getMatrix();
        if (matrix != null) {
            stmt.bindString(5, matrix);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(6, unit);
        }
 
        String qualifier = entity.getQualifier();
        if (qualifier != null) {
            stmt.bindString(7, qualifier);
        }
 
        String measurementText = entity.getMeasurementText();
        if (measurementText != null) {
            stmt.bindString(8, measurementText);
        }
        stmt.bindLong(9, entity.getStationID());
        stmt.bindLong(10, entity.getParameterID());
    }

    @Override
    protected void attachEntity(Measurement entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Measurement readEntity(Cursor cursor, int offset) {
        Measurement entity = new Measurement( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // rowGuid
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // dateMeasured
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // timeMeasured
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // matrix
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // unit
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // qualifier
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // measurementText
            cursor.getLong(offset + 8), // stationID
            cursor.getLong(offset + 9) // parameterID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Measurement entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRowGuid(cursor.getString(offset + 1));
        entity.setDateMeasured(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setTimeMeasured(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setMatrix(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUnit(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setQualifier(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMeasurementText(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStationID(cursor.getLong(offset + 8));
        entity.setParameterID(cursor.getLong(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Measurement entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Measurement entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getStationDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getParameterDao().getAllColumns());
            builder.append(" FROM MEASUREMENT T");
            builder.append(" LEFT JOIN STATION T0 ON T.'STATION_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PARAMETER T1 ON T.'PARAMETER_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Measurement loadCurrentDeep(Cursor cursor, boolean lock) {
        Measurement entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Station station = loadCurrentOther(daoSession.getStationDao(), cursor, offset);
         if(station != null) {
            entity.setStation(station);
        }
        offset += daoSession.getStationDao().getAllColumns().length;

        Parameter parameter = loadCurrentOther(daoSession.getParameterDao(), cursor, offset);
         if(parameter != null) {
            entity.setParameter(parameter);
        }

        return entity;    
    }

    public Measurement loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Measurement> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Measurement> list = new ArrayList<Measurement>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Measurement> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Measurement> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
