package com.amecfw.sage.persistence;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.amecfw.sage.model.ObservationType;
import com.amecfw.sage.model.Station;

import com.amecfw.sage.model.Observation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table OBSERVATION.
*/
public class ObservationDao extends AbstractDao<Observation, Long> {

    public static final String TABLENAME = "OBSERVATION";

    /**
     * Properties of entity Observation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RowGuid = new Property(1, String.class, "rowGuid", false, "ROW_GUID");
        public final static Property Observed = new Property(2, String.class, "observed", false, "OBSERVED");
        public final static Property DateObservered = new Property(3, java.util.Date.class, "dateObservered", false, "DATE_OBSERVERED");
        public final static Property TimeObserved = new Property(4, java.util.Date.class, "timeObserved", false, "TIME_OBSERVED");
        public final static Property StationID = new Property(5, long.class, "stationID", false, "STATION_ID");
        public final static Property ObservationTypeID = new Property(6, long.class, "observationTypeID", false, "OBSERVATION_TYPE_ID");
    };

    private DaoSession daoSession;


    public ObservationDao(DaoConfig config) {
        super(config);
    }
    
    public ObservationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'OBSERVATION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROW_GUID' TEXT NOT NULL UNIQUE ," + // 1: rowGuid
                "'OBSERVED' TEXT," + // 2: observed
                "'DATE_OBSERVERED' INTEGER," + // 3: dateObservered
                "'TIME_OBSERVED' INTEGER," + // 4: timeObserved
                "'STATION_ID' INTEGER NOT NULL ," + // 5: stationID
                "'OBSERVATION_TYPE_ID' INTEGER NOT NULL );"); // 6: observationTypeID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'OBSERVATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Observation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRowGuid());
 
        String observed = entity.getObserved();
        if (observed != null) {
            stmt.bindString(3, observed);
        }
 
        java.util.Date dateObservered = entity.getDateObservered();
        if (dateObservered != null) {
            stmt.bindLong(4, dateObservered.getTime());
        }
 
        java.util.Date timeObserved = entity.getTimeObserved();
        if (timeObserved != null) {
            stmt.bindLong(5, timeObserved.getTime());
        }
        stmt.bindLong(6, entity.getStationID());
        stmt.bindLong(7, entity.getObservationTypeID());
    }

    @Override
    protected void attachEntity(Observation entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Observation readEntity(Cursor cursor, int offset) {
        Observation entity = new Observation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // rowGuid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // observed
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // dateObservered
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // timeObserved
            cursor.getLong(offset + 5), // stationID
            cursor.getLong(offset + 6) // observationTypeID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Observation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRowGuid(cursor.getString(offset + 1));
        entity.setObserved(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDateObservered(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setTimeObserved(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setStationID(cursor.getLong(offset + 5));
        entity.setObservationTypeID(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Observation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Observation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getStationDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getObservationTypeDao().getAllColumns());
            builder.append(" FROM OBSERVATION T");
            builder.append(" LEFT JOIN STATION T0 ON T.'STATION_ID'=T0.'_id'");
            builder.append(" LEFT JOIN OBSERVATION_TYPE T1 ON T.'OBSERVATION_TYPE_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Observation loadCurrentDeep(Cursor cursor, boolean lock) {
        Observation entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Station station = loadCurrentOther(daoSession.getStationDao(), cursor, offset);
         if(station != null) {
            entity.setStation(station);
        }
        offset += daoSession.getStationDao().getAllColumns().length;

        ObservationType observationType = loadCurrentOther(daoSession.getObservationTypeDao(), cursor, offset);
         if(observationType != null) {
            entity.setObservationType(observationType);
        }

        return entity;    
    }

    public Observation loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Observation> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Observation> list = new ArrayList<Observation>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Observation> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Observation> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
