package com.amecfw.sage.persistence;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.amecfw.sage.model.Project;
import com.amecfw.sage.model.Site;

import com.amecfw.sage.model.ProjectSite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PROJECT_SITE.
*/
public class ProjectSiteDao extends AbstractDao<ProjectSite, Long> {

    public static final String TABLENAME = "PROJECT_SITE";

    /**
     * Properties of entity ProjectSite.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RowGuid = new Property(1, String.class, "rowGuid", false, "ROW_GUID");
        public final static Property ProjectID = new Property(2, Long.class, "projectID", false, "PROJECT_ID");
        public final static Property SiteID = new Property(3, Long.class, "siteID", false, "SITE_ID");
    };

    private DaoSession daoSession;


    public ProjectSiteDao(DaoConfig config) {
        super(config);
    }
    
    public ProjectSiteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PROJECT_SITE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROW_GUID' TEXT NOT NULL UNIQUE ," + // 1: rowGuid
                "'PROJECT_ID' INTEGER," + // 2: projectID
                "'SITE_ID' INTEGER);"); // 3: siteID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PROJECT_SITE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ProjectSite entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRowGuid());
 
        Long projectID = entity.getProjectID();
        if (projectID != null) {
            stmt.bindLong(3, projectID);
        }
 
        Long siteID = entity.getSiteID();
        if (siteID != null) {
            stmt.bindLong(4, siteID);
        }
    }

    @Override
    protected void attachEntity(ProjectSite entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ProjectSite readEntity(Cursor cursor, int offset) {
        ProjectSite entity = new ProjectSite( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // rowGuid
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // projectID
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // siteID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ProjectSite entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRowGuid(cursor.getString(offset + 1));
        entity.setProjectID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setSiteID(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ProjectSite entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ProjectSite entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getProjectDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getSiteDao().getAllColumns());
            builder.append(" FROM PROJECT_SITE T");
            builder.append(" LEFT JOIN PROJECT T0 ON T.'PROJECT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN SITE T1 ON T.'SITE_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ProjectSite loadCurrentDeep(Cursor cursor, boolean lock) {
        ProjectSite entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Project project = loadCurrentOther(daoSession.getProjectDao(), cursor, offset);
        entity.setProject(project);
        offset += daoSession.getProjectDao().getAllColumns().length;

        Site site = loadCurrentOther(daoSession.getSiteDao(), cursor, offset);
        entity.setSite(site);

        return entity;    
    }

    public ProjectSite loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ProjectSite> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ProjectSite> list = new ArrayList<ProjectSite>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ProjectSite> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ProjectSite> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
