package com.amecfw.sage.persistence;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.amecfw.sage.model.Location;
import com.amecfw.sage.model.ProjectSite;
import com.amecfw.sage.model.Station;

import com.amecfw.sage.model.Station;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STATION.
*/
public class StationDao extends AbstractDao<Station, Long> {

    public static final String TABLENAME = "STATION";

    /**
     * Properties of entity Station.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RowGuid = new Property(1, String.class, "rowGuid", false, "ROW_GUID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property SurveyDate = new Property(3, java.util.Date.class, "surveyDate", false, "SURVEY_DATE");
        public final static Property SurveyTime = new Property(4, java.util.Date.class, "surveyTime", false, "SURVEY_TIME");
        public final static Property Details = new Property(5, String.class, "details", false, "DETAILS");
        public final static Property Description = new Property(6, String.class, "description", false, "DESCRIPTION");
        public final static Property StationType = new Property(7, String.class, "stationType", false, "STATION_TYPE");
        public final static Property TimeZone = new Property(8, String.class, "timeZone", false, "TIME_ZONE");
        public final static Property LocationID = new Property(9, Long.class, "locationID", false, "LOCATION_ID");
        public final static Property RootID = new Property(10, Long.class, "rootID", false, "ROOT_ID");
        public final static Property ProjectSiteID = new Property(11, Long.class, "projectSiteID", false, "PROJECT_SITE_ID");
    };

    private DaoSession daoSession;


    public StationDao(DaoConfig config) {
        super(config);
    }
    
    public StationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'STATION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROW_GUID' TEXT NOT NULL UNIQUE ," + // 1: rowGuid
                "'NAME' TEXT NOT NULL ," + // 2: name
                "'SURVEY_DATE' INTEGER," + // 3: surveyDate
                "'SURVEY_TIME' INTEGER," + // 4: surveyTime
                "'DETAILS' TEXT," + // 5: details
                "'DESCRIPTION' TEXT," + // 6: description
                "'STATION_TYPE' TEXT NOT NULL ," + // 7: stationType
                "'TIME_ZONE' TEXT," + // 8: timeZone
                "'LOCATION_ID' INTEGER," + // 9: locationID
                "'ROOT_ID' INTEGER," + // 10: rootID
                "'PROJECT_SITE_ID' INTEGER);"); // 11: projectSiteID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Station entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRowGuid());
        stmt.bindString(3, entity.getName());
 
        java.util.Date surveyDate = entity.getSurveyDate();
        if (surveyDate != null) {
            stmt.bindLong(4, surveyDate.getTime());
        }
 
        java.util.Date surveyTime = entity.getSurveyTime();
        if (surveyTime != null) {
            stmt.bindLong(5, surveyTime.getTime());
        }
 
        String details = entity.getDetails();
        if (details != null) {
            stmt.bindString(6, details);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(7, description);
        }
        stmt.bindString(8, entity.getStationType());
 
        String timeZone = entity.getTimeZone();
        if (timeZone != null) {
            stmt.bindString(9, timeZone);
        }
 
        Long locationID = entity.getLocationID();
        if (locationID != null) {
            stmt.bindLong(10, locationID);
        }
 
        Long rootID = entity.getRootID();
        if (rootID != null) {
            stmt.bindLong(11, rootID);
        }
 
        Long projectSiteID = entity.getProjectSiteID();
        if (projectSiteID != null) {
            stmt.bindLong(12, projectSiteID);
        }
    }

    @Override
    protected void attachEntity(Station entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Station readEntity(Cursor cursor, int offset) {
        Station entity = new Station( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // rowGuid
            cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // surveyDate
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // surveyTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // details
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // description
            cursor.getString(offset + 7), // stationType
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // timeZone
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // locationID
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // rootID
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11) // projectSiteID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Station entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRowGuid(cursor.getString(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setSurveyDate(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setSurveyTime(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setDetails(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDescription(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setStationType(cursor.getString(offset + 7));
        entity.setTimeZone(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLocationID(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setRootID(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setProjectSiteID(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Station entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Station entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLocationDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getStationDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getProjectSiteDao().getAllColumns());
            builder.append(" FROM STATION T");
            builder.append(" LEFT JOIN LOCATION T0 ON T.'LOCATION_ID'=T0.'_id'");
            builder.append(" LEFT JOIN STATION T1 ON T.'ROOT_ID'=T1.'_id'");
            builder.append(" LEFT JOIN PROJECT_SITE T2 ON T.'PROJECT_SITE_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Station loadCurrentDeep(Cursor cursor, boolean lock) {
        Station entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Location location = loadCurrentOther(daoSession.getLocationDao(), cursor, offset);
        entity.setLocation(location);
        offset += daoSession.getLocationDao().getAllColumns().length;

        Station station = loadCurrentOther(daoSession.getStationDao(), cursor, offset);
        entity.setStation(station);
        offset += daoSession.getStationDao().getAllColumns().length;

        ProjectSite projectSite = loadCurrentOther(daoSession.getProjectSiteDao(), cursor, offset);
        entity.setProjectSite(projectSite);

        return entity;    
    }

    public Station loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Station> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Station> list = new ArrayList<Station>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Station> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Station> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
