package com.amecfw.sage.model;

import java.util.List;
import com.amecfw.sage.persistence.DaoSession;
import de.greenrobot.dao.DaoException;

import com.amecfw.sage.persistence.MeasurementDao;
import com.amecfw.sage.persistence.MeasurementMetaDao;
import com.amecfw.sage.persistence.ParameterDao;
import com.amecfw.sage.persistence.StationDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.UUID;
import java.io.IOException;

import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserException;
import org.xmlpull.v1.XmlSerializer;
// KEEP INCLUDES END
/**
 * Entity mapped to table MEASUREMENT.
 */
public class Measurement extends EntityBase  implements UUIDSupport, MetaDataSupport<MeasurementMeta> {

    private Long id;
    /** Not-null value. */
    private String rowGuid;
    private java.util.Date dateMeasured;
    private java.util.Date timeMeasured;
    private String matrix;
    private String unit;
    private String qualifier;
    private String measurementText;
    private long stationID;
    private long parameterID;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MeasurementDao myDao;

    private Station station;
    private Long station__resolvedKey;

    private Parameter parameter;
    private Long parameter__resolvedKey;

    private List<MeasurementMeta> metaData;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Measurement() {
    }

    public Measurement(Long id) {
        this.id = id;
    }

    public Measurement(Long id, String rowGuid, java.util.Date dateMeasured, java.util.Date timeMeasured, String matrix, String unit, String qualifier, String measurementText, long stationID, long parameterID) {
        this.id = id;
        this.rowGuid = rowGuid;
        this.dateMeasured = dateMeasured;
        this.timeMeasured = timeMeasured;
        this.matrix = matrix;
        this.unit = unit;
        this.qualifier = qualifier;
        this.measurementText = measurementText;
        this.stationID = stationID;
        this.parameterID = parameterID;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMeasurementDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRowGuid() {
        return rowGuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRowGuid(String rowGuid) {
        this.rowGuid = rowGuid;
    }

    public java.util.Date getDateMeasured() {
        return dateMeasured;
    }

    public void setDateMeasured(java.util.Date dateMeasured) {
        this.dateMeasured = dateMeasured;
    }

    public java.util.Date getTimeMeasured() {
        return timeMeasured;
    }

    public void setTimeMeasured(java.util.Date timeMeasured) {
        this.timeMeasured = timeMeasured;
    }

    public String getMatrix() {
        return matrix;
    }

    public void setMatrix(String matrix) {
        this.matrix = matrix;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getQualifier() {
        return qualifier;
    }

    public void setQualifier(String qualifier) {
        this.qualifier = qualifier;
    }

    public String getMeasurementText() {
        return measurementText;
    }

    public void setMeasurementText(String measurementText) {
        this.measurementText = measurementText;
    }

    public long getStationID() {
        return stationID;
    }

    public void setStationID(long stationID) {
        this.stationID = stationID;
    }

    public long getParameterID() {
        return parameterID;
    }

    public void setParameterID(long parameterID) {
        this.parameterID = parameterID;
    }

    /** To-one relationship, resolved on first access. */
    public Station getStation() {
        long __key = this.stationID;
        if (station__resolvedKey == null || !station__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            StationDao targetDao = daoSession.getStationDao();
            Station stationNew = targetDao.load(__key);
            synchronized (this) {
                station = stationNew;
            	station__resolvedKey = __key;
            }
        }
        return station;
    }

    public void setStation(Station station) {
        if (station == null) {
            throw new DaoException("To-one property 'stationID' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.station = station;
            stationID = station.getId();
            station__resolvedKey = stationID;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Parameter getParameter() {
        long __key = this.parameterID;
        if (parameter__resolvedKey == null || !parameter__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ParameterDao targetDao = daoSession.getParameterDao();
            Parameter parameterNew = targetDao.load(__key);
            synchronized (this) {
                parameter = parameterNew;
            	parameter__resolvedKey = __key;
            }
        }
        return parameter;
    }

    public void setParameter(Parameter parameter) {
        if (parameter == null) {
            throw new DaoException("To-one property 'parameterID' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.parameter = parameter;
            parameterID = parameter.getId();
            parameter__resolvedKey = parameterID;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<MeasurementMeta> getMetaData() {
        if (metaData == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MeasurementMetaDao targetDao = daoSession.getMeasurementMetaDao();
            List<MeasurementMeta> metaDataNew = targetDao._queryMeasurement_MetaData(id);
            synchronized (this) {
                if(metaData == null) {
                    metaData = metaDataNew;
                }
            }
        }
        return metaData;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetMetaData() {
        metaData = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public boolean hasMetaData(){
    	if(id == null || id < 1){
    		if(metaData == null || metaData.size() < 1) return false;
    		return true;
    	}else{
    		try{
    			getMetaData();
    			if(metaData == null || metaData.size() < 1) return false;
        		return true;
    		}catch(DaoException e){
    			return false;
    		}
    	}
    }
    
    @Override
	public void setMetaData(List<MeasurementMeta> metaData) {
		this.metaData = metaData;		
	}
    
    @Override
   	public UUID getUUID() {
       	return uuidFromString(rowGuid);
   	}

   	@Override
   	public void setUUID(UUID rowGuid) {
   		this.rowGuid = uuidFromUUID(rowGuid); 
   		
   	}

   	@Override
   	public void generateUUID() {
   		rowGuid = UUID.randomUUID().toString();
   	}
   	
   	/**
   	 * Generates a new id by calling generateUUID()
   	 * @see com.amecfw.sage.vegapp.model.UUIDSupport#setRowGuid()
   	 */
   	@Override
   	public void setRowGuid(){
   		generateUUID();
   	}
       
       @Override
   	public void fromXml(XmlPullParser parser) throws XmlPullParserException,
   			IOException {
   		// TODO Auto-generated method stub
   		
   	}

   	@Override
   	public void toXml(XmlSerializer serializer) throws XmlPullParserException,
   			IOException {
   		// TODO Auto-generated method stub
   		
   	}
    // KEEP METHODS END

}
